apiVersion: v1
kind: Service
metadata:
  name: flaskdemo-service
spec:
  selector:
    app: flaskdemo-pod
  ports: 
  - port: 6000
    targetPort: 5001
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo-deployment
spec:
  selector:
    matchLabels:
      app: flaskdemo-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskdemo-pod
    spec:
      containers:
      - name: flaskdemo-container
        image: nakash100507/flaskdemo:latestv2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5001